name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has been in the Awaiting Reply state for 14 days without a response. If no reply is provided within the next 7 days, it will be closed.'
          close-issue-message: 'This issue has been closed due to a lack of recent activity after being marked as stale.'
          days-before-stale: 14
          days-before-close: 7
          days-before-pr-close: -1
          stale-issue-label: 'state: Stale'
          only-issue-labels: 'state: Awaiting Reply :speaking_head:'
          operations-per-run: 100